max_line_length = 160

std = {
  -- Solar2D API and other global libraries.
  globals = {
    "_G",
    "al",
    "assert",
    "audio",
    "cloneArray",
    "collectgarbage",
    "coronabaselib",
    "coroutine",
    "debug",
    "display",
    "dofile",
    "easing",
    "error",
    "gcinfo",
    "getfenv",
    "getmetatable",
    "graphics",
    "io",
    "ipairs",
    "lfs",
    "load",
    "loadfile",
    "loadstring",
    "lpeg",
    "math",
    "media",
    "metatable",
    "module",
    "native",
    "network",
    "newproxy",
    "next",
    "os",
    "package",
    "pairs",
    "pcall",
    "physics",
    "print",
    "rawequal",
    "rawget",
    "rawset",
    "require",
    "Runtime",
    "select",
    "sendLaunchAnalytics",
    "setfenv",
    "setmetatable",
    "string",
    "system",
    "table",
    "timer",
    "tonumber",
    "tostring",
    "transition",
    "type",
    "unpack",
    "xpcall",
    "application",
    "settings",
    "utils",
  }
}
-- Commonly used Solar2D/Lua 5.1 function arguments,
-- as well as Luacheck configuration's own globals.
ignore = {
  "self",
  "event",
  "arg",
  "ignore",
  "std",
  "max_line_length",
}